name: Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag name
        id: tag
        uses: actions/github-script@v7
        with:
          script: return context.payload.release.tag_name

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          file: Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_LOGIN }}/${{ vars.DOCKERHUB_IMAGE }}:${{ fromJSON(steps.tag.outputs.result) }}
            ${{ vars.DOCKERHUB_LOGIN }}/${{ vars.DOCKERHUB_IMAGE }}:latest
